### ISSUE TITLE
视频下载不完全的问题

### ISSUE THREAD

**Issue by VinciJoy** [Okery/Bilibili-Video-Downloader#1]
你好，我发现--page 0时，部分视频下载不完全，这部分是因为什么原因导致的呢。是多线程，还是因为我暂停后重新开始亦或是我同时进行多个下载任务？感谢解答。

**Comment by VinciJoy** [comment]
--max-workers设置不了进程数量，手动把进程数量改成1之后问题消失，意思是多进程的话下载不完全，单进程没问题，不知道是不是只有我有这个问题。

**Comment by VinciJoy** [comment]
--max-workers设置不了进程数量，手动把进程数量改成1之后问题没有消失，但是能多下一部分了，我把downloader里的写文件部分改了问题消失
`            res = requests.get(play_url, headers=headers, stream=True)
            length = int(res.headers['Content-Length'])
            print(f'\n    size: {unit_convert(length)}')
            with open(file_path, 'wb') as f:
                for data in res.iter_content(chunk_size=1024 * 1024):
                    count += len(data)
                    f.write(data)
                    # print('\r    {:5.1f}%'.format((count / length) * 100), end='')

            os.rename(file_path, done_file_path)`

**Comment by Okery** [comment]
关于--max-workers 设置不了：

抱歉，这是我的疏忽。
```main.py```文件第 28 行 ```args.max_workers = cpu_count() // 2```是多余的，删掉这一行。
第 3 行```from multiprocessing import cpu_count```也是多余的。

**Comment by VinciJoy** [comment]
你好，我增加了断点续传和请求超时重试功能，已经完美解决下载不完整问题，已经提交了。

**Comment by Okery** [comment]
在命令行中有时会遇到无法下载全部视频的问题。

将```--url https://www.bilibili.com/video/BV1Zb411q7Nk?from=search&seid=4218745237610208220```
改成```--url https://www.bilibili.com/video/BV1Zb411q7Nk```
即去掉 url 中的参数

**Comment by VinciJoy** [comment]
是单个视频下载不完整，只能下100mb左右。

**Comment by VinciJoy** [comment]
猜测是请求视频数据太大导致的缓存问题，通过分块请求下载已经解决了。

**Comment by Okery** [comment]
发下视频网址，我测试一下

**Comment by VinciJoy** [comment]
https://www.bilibili.com/video/BV1pt411h7aT

**Comment by VinciJoy** [comment]
单个视频体积小，但是p多的后面的p都只下载几b，可能是因为缓存问题。

**Comment by VinciJoy** [comment]
我用的是ubuntu不是windows，如果你没有这种情况可能是两个操作系统内存管理不一样导致。
